baseURL = "https://blog.ginuerzh.xyz/"
DefaultContentLanguage = "zh"
title = "ginuerzh"
theme = "beautifulhugo"
hasCJKLanguage = true
disqusShortname = "blog-ginuerzh-xyz"
googleAnalytics = "UA-98791308-1"

[params]
  #subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png"
  # favicon = "img/favicon.ico"
  # dateFormat = "January 2, 2006" # default date format
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[params.bigimg]]
  src = "img/sunset.jpg"
  desc = "Sunset"
[[params.bigimg]]
  src = "img/dishuilake.jpg"
  desc = "Dishui Lake"
[[params.bigimg]]
  src = "img/wetland.jpg"
  desc = "Dongtan Wetland"

[author]
  name = "Gerry"
  email = "ginuerzh@gmail.com"
  facebook = "ginuerzh"
  googleplus = "107672470345374793796"
  github = "ginuerzh"
  twitter = "ginuerzh"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  stackoverflow = "users/2013767/ginuerzh"
  # snapchat = "username"
  # instagram = "username"
  youtube = "user/ginuerzh" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"

# [languages.en]
#   weight = 0
#   languageName = "English"
#
# [[languages.en.menu.main]]
#   name = "Categories"
#   url = "categories/"
#   weight = 1
#
# [[languages.en.menu.main]]
#   name = "Tags"
#   url = "tags/"
#   weight = 2
#
# [[languages.en.menu.main]]
#   name = "About"
#   url = "about/"
#   weight = 3

[languages.zh]
  weight = 1
  languageName = "中文"

[[languages.zh.menu.main]]
  name = "目录"
  url = "categories/"
  weight = 1

[[languages.zh.menu.main]]
  name = "标签"
  url = "tags/"
  weight = 2

[[languages.zh.menu.main]]
  name = "关于"
  url = "about/"
  weight = 3
